#!/bin/bash
#
# Create Kubernetes cluster using "kind" and custom config file
#

echo ""
echo "Creating cluster..."
kind create cluster --config=cluster.yaml
if (( $? )); then echo "Failed to create cluster"; echo ""; exit 1; fi
echo "Successfuly created cluster"
echo ""

#::END""
