#!/bin/bash
#
# Delete Kubernetes cluster created using "kind"
#

source utils.sh

echo ""
while getopts "n:h" opt ${@}; do
        case ${opt} in
                n)
                        clusterName=${OPTARG}
                        ;;
                h)
                        echo "Usage: "
                        echo "        delete-cluster [-n cluster-name]"
                        echo ""
                        echo "        If cluster name is not provided then default kind cluster is delete"
                        echo ""
                        exit 0
                        ;;
        esac
done

readonly CLUSTER_NAME=${clusterName:-kind}

echo "Deleting [${CLUSTER_NAME}] cluster..."
if ( isClusterExist ${CLUSTER_NAME} ); then
	read -p "Are you sure you want to delete [${CLUSTER_NAME}] cluster? [Y/N] " -n1 userResponse
	echo ""
	if [[ "${userResponse,,}" == "y" ]]; then
		kind delete cluster --name=${CLUSTER_NAME} 
		if (( $? )); then 
			echo "Failed to delete cluster"
		else 
			echo "Deleted the cluster"
		fi
	else
		echo "Not deleting the cluster."
	fi
else
	echo "[${CLUSTER_NAME}] cluster doesn't exist."
fi 
echo ""

#::END::
