version: "3"


services: 
  nginx:
    image: nginx
    network_mode: "host"
    restart: always
#   ports:
#     - 3001:80
    volumes:
      - ./content:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

