#!/bin/bash
#
# Start proxy
#

readonly PROXY_PORT=8001

echo ""
readonly PS_COUNT=$(netstat -antp 2> /dev/null | grep kubectl | grep 8001 | wc -l)
if (( ${PS_COUNT} > 0 )); then echo "Proxy already running..."; echo ""; exit 0; fi

echo "Starting proxy on port ${PROXY_PORT}..."
kubectl proxy --port=${PROXY_PORT} > /dev/null 2>&1 &
if (( $? )); then echo "Failed to start proxy"; echo ""; exit 1; fi

echo "Proxy started on port ${PROXY_PORT}"
echo "You can access the Kubernetes dashboard at the following URL:"
echo "http://localhost:${PROXY_PORT}/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy"
echo ""

#::END:: 
