#!/bin/bash
#
# Start proxy
# 

source utils.sh
source config/proxy.conf

echo ""
while getopts "n:p:h" opt ${@}; do
        case ${opt} in
                n)
                        clusterName=${OPTARG}
                        ;;
                p)
                        proxyPort=${OPTARG}
                        ;;
                h)
                        echo "Usage: "
                        echo "        start-proxy [-n cluster-name] [-p proxy-port]"
                        echo ""
                        echo "        The default values are:"
                        echo "        Cluster name  : kind"
                        echo "        Proxy port    : RANDOM PORT"
                        echo ""
                        exit 0
                        ;;
        esac
done

readonly CLUSTER_NAME="${clusterName:-kind}"
readonly CTX_NAME="kind-${clusterName:-kind}"
readonly PROXY_PORT_FILE="${DATA_DIR}/${CTX_NAME}"
readonly PROXY_STATUS_FILE="${DATA_DIR}/${CTX_NAME}-status"

echo "Starting proxy..."
if ! ( isClusterExist ${CLUSTER_NAME} ); then 
        abort "Cannot create proxy. [${CLUSTER_NAME}] cluster doesn't exists."
fi 
if [ ! -d ${DATA_DIR} ]; then
	mkdir -p ${DATA_DIR}
	if (( $? )); then
		abort "Failed to create data directory [${DATA_DIR}] to store running proxy server's port number"
	fi
fi 
if [ -f ${PROXY_PORT_FILE} ]; then
	source ${PROXY_PORT_FILE}
	#echo "******* PROXY PORT=[${PROXY_PORT}] ********** "
	readonly PS_COUNT=$(netstat -antp 2> /dev/null | grep kubectl | grep ${PROXY_PORT} | wc -l)
	if (( ${PS_COUNT} > 0 )); then 
		abort "Proxy already running..."
	fi 
fi
PROXY_PORT="${proxyPort:-0}"
echo "Setting current context to [${CTX_NAME}]..."
kubectl config use-context ${CTX_NAME}
kubectl proxy --port=${PROXY_PORT} > ${PROXY_STATUS_FILE} 2>&1 &
sleep 3
if (( $? )); then abort "Failed to start proxy"; fi
PROXY_PORT=$(cat ${PROXY_STATUS_FILE} | grep -i "starting to serve on" | sed 's/.*://')
echo "PROXY_PORT=${PROXY_PORT}" > ${PROXY_PORT_FILE} 
echo "Proxy started on port ${PROXY_PORT}"
echo "You can access the Kubernetes dashboard at the following URL:"
echo "http://localhost:${PROXY_PORT}/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy"
echo ""

#::END:: 
