#!/bin/bash
#
# Stop proxy
#

source utils.sh
source config/proxy.conf

function getProcessCount
{
	local _checkData=${1}
	if [ -z ${_checkData} ]; then
		echo 0
	else
		echo $(echo ${_checkData} | wc -l)
	fi
}

echo ""
while getopts "n:h" opt ${@}; do
        case ${opt} in
                n)
                        clusterName=${OPTARG}
                        ;;
                h)
                        echo "Usage: "
                        echo "        stop-proxy [-n cluster-name]"
                        echo ""
                        echo "        The default cluster name is [kind]"
                        echo ""
                        exit 0
                        ;;
        esac
done

readonly CLUSTER_NAME=${clusterName:-kind}
readonly CTX_NAME="kind-${clusterName:-kind}"
readonly PROXY_DATA_FILE=${DATA_DIR}/${CTX_NAME}

echo "Stopping proxy for [${CLUSTER_NAME}] cluster..."
if [ ! -f ${PROXY_DATA_FILE} ]; then
	abort "Unable to locate proxy data file [${PROXY_DATA_FILE}] for [${CLUSTER_NAME}] cluster"
fi
source ${PROXY_DATA_FILE} 
readonly checkData=$(netstat -antp 2> /dev/null | grep kubectl | grep ${PROXY_PORT})
if (( $(getProcessCount ${checkData}) == 0 )); then 
	abort "Proxy not running..."; 
fi 
readonly processId=$(echo $checkData | awk '{print $7}' | awk 'BEGIN { FS = "/" } ; {print $1}')
kill -9 ${processId} > /dev/null 2>&1
if (( $? )); then echo "Failed to stop proxy"; echo ""; exit 1; fi 
echo "Successfully stopped proxy"
echo ""

#::END:: 
