#!/bin/bash
#
# 
# 

isClusterExist() {
	local clusterName=${1}
	local clustersList=($(kind get clusters 2> /dev/null))
	local clustersCount=${#clustersList[@]}
	if (( $clustersCount > 0 )) && [[ " ${clustersList[@]} " =~ " ${clusterName} " ]]; then
		exit 0
	else
		exit 1
	fi 
}

clusterHelp() {
	echo ""
	echo "Usage: "
	echo "  create-cluster [-c config-YAML-file] [-n cluster-name]"
	echo ""
	echo "  If no options are provided then default kind cluster is created"
	echo ""
}

#
# Create Kubernetes cluster using "kind" 
#

createCluster() {
	echo "\$@ = $@"
	local configFile=""
	local clusterName="" 

	echo ""
	while getopts "c:n:h" opt ${@}; do
		case ${opt} in
			c) configFile=${OPTARG} ;; 
			n) clusterName=${OPTARG} ;; 
			h) clusterHelp && exit 0 ;;
		esac
	done

	if [[ ! -z "${configFile}" && ! -f ${configFile} ]]; then 
		abort "Config file [${configFile}] doesn't exist. aborting..."; 
	fi
	readonly CONFIG_FILE=${configFile}
	readonly CLUSTER_NAME=${clusterName:-kind}
	readonly CTX_NAME="kind-${clusterName:-kind}" 
	echo ""
	echo "Creating cluster..."
	echo ""
	echo "  Cluster name      : ${CLUSTER_NAME}"
	echo "  Cluster context   : ${CTX_NAME}"
	echo "  Configuration file: ${CONFIG_FILE}"
	echo "" 
	if ( isClusterExist ${CLUSTER_NAME} ); then
		abort "Cannot create.  [${CLUSTER_NAME}] cluster exists."
	fi
	if [[ -z "${CONFIG_FILE}" ]]; then
		kind create cluster --name=${CLUSTER_NAME}
	else
		kind create cluster --config=${CONFIG_FILE} --name=${CLUSTER_NAME}
	fi
	if (( $? )); then echo "Failed to create cluster"; echo ""; exit 1; fi
	echo "Successfuly created cluster"
	echo ""
}

#
# Delete Kubernetes cluster created using "kind"
#

deleteCluster() {
	echo ""
	while getopts "n:h" opt ${@}; do
		case ${opt} in
			n) clusterName=${OPTARG} ;;
			h)
				echo "Usage: "
				echo "        deleteCluster [-n cluster-name]"
				echo ""
				echo "        If cluster name is not provided then default kind cluster is deleted"
				echo ""
				exit 0
				;;
		esac
	done

	readonly CLUSTER_NAME=${clusterName:-kind}

	echo "Deleting [${CLUSTER_NAME}] cluster..."
	if ( isClusterExist ${CLUSTER_NAME} ); then
		read -p "Are you sure you want to delete [${CLUSTER_NAME}] cluster? [Y/N] " -n1 userResponse
		echo ""
		if [[ "${userResponse,,}" == "y" ]]; then
			kind delete cluster --name=${CLUSTER_NAME} 
			if (( $? )); then 
				echo "Failed to delete cluster"
			else 
				echo "Deleted the cluster"
			fi
		else
			echo "Not deleting the cluster."
		fi
	else
		echo "[${CLUSTER_NAME}] cluster doesn't exist."
	fi 
	echo ""
}

#::END::
